# Dev configuration

[clients.auth]
user = "papernet_admin"
password = "papernet"
baseURL = "http://127.0.0.1:1705"

# ----------------------------------------
# Auth service
[auth]
key = "configuration/hs256.json"

[auth.cayley]
store = "data/auth.graph"
# Auth service
# ----------------------------------------

# ----------------------------------------
# Oauth service
[oauth]
# bolt="data/oauth.db"
# file="configuration/oauth_google.json"
email = true
google = true
# Oauth service
# ----------------------------------------

# ----------------------------------------
# Google service
[google]
bolt = "data/google.db"
file = "configuration/oauth_google.json"
key = "configuration/hs256.json"

# ----------------------------------------
# Imports service
[imports]
paperURL="http://127.0.0.1:1705/paper/v2/papers"
key = "configuration/hs256.json"

[imports.bolt]
store = "data/imports.db"
# Imports service
# ----------------------------------------

# ----------------------------------------
# Paper service
[paper]
key = "configuration/hs256.json"

[paper.bolt]
store = "data/paper.db"

[paper.bleve]
store = "data/paper.index"
# Paper service
# ----------------------------------------

[bolt]
store = "data/papernet.db"

[bleve]
store = "data/papernet.index"
